module.exports = [
  {
    type: "heading",
    defaultValue: "Paradroid 2000",
  },
  {
    type: "section",
    items: [
      {
        type: "heading",
        defaultValue: "Time Settings",
      },
      {
        type: "select",
        messageKey: "COLOR_INDEX",
        label: "Time colour",
        defaultValue: "0",
        options: [
          { label: "White", value: "0" },
          { label: "Green", value: "1" },
          { label: "Yellow", value: "2" },
          { label: "Cyan", value: "3" },
          { label: "Orange", value: "4" },
        ],
      },
    ],
  },
  {
    type: "section",
    items: [
      {
        type: "heading",
        defaultValue: "Droid Settings",
      },
      {
        type: "select",
        messageKey: "DROID_SELECT",
        label: "Droid",
        defaultValue: "0",
        options: [
          { label: "Random", value: "0" },
          { label: "001", value: "1" },
          { label: "123", value: "2" },
          { label: "139", value: "3" },
          { label: "247", value: "4" },
          { label: "249", value: "5" },
          { label: "296", value: "6" },
          { label: "302", value: "7" },
          { label: "329", value: "8" },
          { label: "420", value: "9" },
          { label: "476", value: "10" },
          { label: "493", value: "11" },
          { label: "516", value: "12" },
          { label: "571", value: "13" },
          { label: "598", value: "14" },
          { label: "614", value: "15" },
          { label: "615", value: "16" },
          { label: "629", value: "17" },
          { label: "711", value: "18" },
          { label: "742", value: "19" },
          { label: "751", value: "20" },
          { label: "821", value: "21" },
          { label: "834", value: "22" },
          { label: "883", value: "23" },
          { label: "999", value: "24" },
        ],
      },
      {
        type: "select",
        messageKey: "DROID_CHANGE",
        label: "Change droid every",
        defaultValue: "1",
        options: [
          { label: "Never", value: "0" },
          { label: "1 Minute", value: "1" },
          { label: "5 Minutes", value: "5" },
          { label: "10 Minutes", value: "10" },
          { label: "30 Minutes", value: "30" },
          { label: "60 Minutes", value: "60" },
        ],
      },
    ],
  },
  {
    type: "section",
    items: [
      {
        type: "heading",
        defaultValue: "Quiet Time Settings",
      },
      {
        type: "toggle",
        messageKey: "DROID_QUIET_TIME",
        label: "Don't change droid at these times",
        defaultValue: false,
      },
      {
        type: "slider",
        messageKey: "DROID_QUIET_START",
        defaultValue: 23,
        label: "Changes stop at (24hr)",
        min: 0,
        max: 23,
      },
      {
        type: "slider",
        messageKey: "DROID_QUIET_STOP",
        defaultValue: 6,
        label: "Changes resume at (24hr)",
        min: 0,
        max: 23,
      },
    ],
  },
  {
    type: "submit",
    defaultValue: "Save Settings",
  },
];
